const getFormUserPositionsConst = {
    GET_FORM_USER_POSITIONS: "GET_FORM_USER_POSITIONS",
    GET_FORM_USER_POSITIONS_SUCCESS: "GET_FORM_USER_POSITIONS_SUCCESS",
    GET_FORM_USER_POSITIONS_ERROR: "GET_FORM_USER_POSITIONS_ERROR",
};


export default getFormUserPositionsConst;