const registrationUserConst = {
    REGISTRATION_NEW_USER: "REGISTRATION_NEW_USER",
    REGISTRATION_NEW_USER_SUCCESS: "REGISTRATION_NEW_USER_SUCCESS",
    REGISTRATION_NEW_USER_ERROR: "REGISTRATION_NEW_USER_ERROR",
    CLEAR_DATA: "CLEAR_DATA",
};

export default registrationUserConst;